version: "3"

services:
  database:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "12017:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: alert1521/ci-cd:1.0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on:
      - database


volumes:
  data_db: