# name: CI/CD docker-compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci_cd:

    runs-on: ubuntu-20.04

    steps:
    -
      uses: actions/checkout@v2
      name: go-test
      run: 
        go test --short

    -
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
